# ==========================================================
# Glass_Structure_Analysis_Ovito.py
# Author: Neha
# Institution: COMSATS University Islamabad
# Description:
#   Comprehensive structural analysis of amorphous glass
#   generated by LAMMPS simulations.
#   Computes RDF, S(q), coordination, ring sizes,
#   and bond-angle distributions using the OVITO Python API.
# ==========================================================
import ovito
from ovito.io import import_file
from ovito.modifiers import CoordinationAnalysisModifier, CreateBondsModifier
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
import os

# ==========================
# 0. Output directory
# ==========================
script_dir = r"file path"
output_dir = script_dir
# ==========================
plt.style.use("seaborn-v0_8-paper")
plt.rcParams.update({
    "font.size": 16,
    "axes.labelsize": 18,
    "axes.titlesize": 18,
    "legend.fontsize": 14,
    "xtick.labelsize": 14,
    "ytick.labelsize": 14,
    "lines.linewidth": 2,
    "figure.dpi": 600
})
# ==========================
def compute_rdf_sq(pipeline, frame=0, bins=200, r_cut=8.0):
    pipeline.modifiers.clear()
    rdf_mod = CoordinationAnalysisModifier(cutoff=r_cut, number_of_bins=bins)
    rdf_mod.partial = False
    pipeline.modifiers.append(rdf_mod)
    data = pipeline.compute(frame=frame)
    rdf_table = data.tables['coordination-rdf']
    r = np.array(rdf_table.xy()[:,0])
    g_r = np.array(rdf_table.xy()[:,1])
    rho = len(data.particles['Position']) / pipeline.source.data.cell.volume
    dr = r[1]-r[0]
    q = np.linspace(0.1, 20, 500)
    S_q = np.array([1 + 4*np.pi*rho*np.sum((r**2)*(g_r-1)*np.sin(qi*r)/(qi*r)*dr) for qi in q])
    return r, g_r, q, S_q

def compute_coordination(pipeline, frame=0, cutoff=2.3):
    pipeline.modifiers.clear()
    cn_mod = CoordinationAnalysisModifier(cutoff=cutoff)
    pipeline.modifiers.append(cn_mod)
    data = pipeline.compute(frame=frame)
    return np.array(data.particles['Coordination'])

def compute_rings(pipeline, frame=0, cutoff=2.3):
    pipeline.modifiers.clear()
    pipeline.modifiers.append(CreateBondsModifier(cutoff=cutoff))
    data = pipeline.compute(frame=frame)

    bonds = data.particles.bonds
    topology = bonds.topology
    n_particles = data.particles.count

    neighbors_dict = {i: [] for i in range(n_particles)}
    for b in topology:
        i, j = int(b[0]), int(b[1])
        neighbors_dict[i].append(j)
        neighbors_dict[j].append(i)

    # Build networkx graph
    G = nx.Graph()
    for i, nbrs in neighbors_dict.items():
        for j in nbrs:
            if i < j:
                G.add_edge(i, j)

    rings = list(nx.cycle_basis(G))
    ring_sizes = [len(r) for r in rings]
    if len(ring_sizes) == 0:
        return np.array([]), np.array([])
    unique_sizes, counts = np.unique(ring_sizes, return_counts=True)
    return unique_sizes, counts

def compute_bond_angles(pipeline, frame=0, cutoff=2.3, central_atom_type=1):
    """Compute bond angles centered on specified atom type.
       central_atom_type=1 -> Si (for O–Si–O)
       central_atom_type=2 -> O  (for Si–O–Si)
    """
    pipeline.modifiers.clear()
    pipeline.modifiers.append(CreateBondsModifier(cutoff=cutoff))
    data = pipeline.compute(frame=frame)

    positions = data.particles['Position']
    types = data.particles['Particle Type']
    bonds = data.particles.bonds
    topology = bonds.topology
    n_particles = data.particles.count

    neighbors_dict = {i: [] for i in range(n_particles)}
    for b in topology:
        i, j = int(b[0]), int(b[1])
        neighbors_dict[i].append(j)
        neighbors_dict[j].append(i)

    angles_list = []
    for i, t in enumerate(types):
        if t == central_atom_type:
            nbrs = neighbors_dict[i]
            if len(nbrs) >= 2:
                for j in range(len(nbrs)):
                    for k in range(j+1, len(nbrs)):
                        v1 = positions[nbrs[j]] - positions[i]
                        v2 = positions[nbrs[k]] - positions[i]
                        cos_angle = np.dot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))
                        angles_list.append(np.degrees(np.arccos(np.clip(cos_angle,-1.0,1.0))))
    return angles_list
# ==========================
pipeline = import_file(os.path.join(script_dir,"file"))
nframes = pipeline.source.num_frames

# ==========================
# Compute properties (first & last frame)
# ==========================
r1, g_r1, q1, S_q1 = compute_rdf_sq(pipeline, frame=0)
r2, g_r2, q2, S_q2 = compute_rdf_sq(pipeline, frame=nframes-1)
cn1 = compute_coordination(pipeline, frame=0)
cn2 = compute_coordination(pipeline, frame=nframes-1)
rings_sizes1, rings_counts1 = compute_rings(pipeline, frame=0)
rings_sizes2, rings_counts2 = compute_rings(pipeline, frame=nframes-1)

# Bond angles
# O–Si–O angles: central_atom_type=1
angles_O_Si_O_1 = compute_bond_angles(pipeline, frame=0, central_atom_type=1)
angles_O_Si_O_2 = compute_bond_angles(pipeline, frame=nframes-1, central_atom_type=1)

# Si–O–Si angles: central_atom_type=2
angles_Si_O_Si_1 = compute_bond_angles(pipeline, frame=0, central_atom_type=2)
angles_Si_O_Si_2 = compute_bond_angles(pipeline, frame=nframes-1, central_atom_type=2)

# ==========================
# Plot RDF
# ==========================
plt.figure()
plt.plot(r1, g_r1, color='blue', label='Before Amorphous')
plt.plot(r2, g_r2, color='red', label='After Amorphous')
plt.xlabel('r (Å)')
plt.ylabel('g(r)')
plt.title('RDF Comparison')
plt.xlim(0, 6)
plt.ylim(0, max(g_r1.max(), g_r2.max())*1.1)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"rdf_comparison.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"rdf_comparison.svg"))
plt.close()

# ==========================
# Structure Factor
# ==========================
plt.figure()
plt.plot(q1, S_q1, color='blue', label='Before Amorphous')
plt.plot(q2, S_q2, color='red', label='After Amorphous')
plt.xlabel('q (1/Å)')
plt.ylabel('S(q)')
plt.title('Structure Factor Comparison')
plt.xlim(0, 10)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"structure_factor_comparison.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"structure_factor_comparison.svg"))
plt.close()

# ==========================
# Coordination
# ==========================
plt.figure()
plt.hist(cn1, bins=np.arange(0,10), alpha=0.5, label='Before Amorphous', edgecolor='black')
plt.hist(cn2, bins=np.arange(0,10), alpha=0.5, label='After Amorphous', edgecolor='black')
plt.xlabel('Coordination number')
plt.ylabel('Count')
plt.title('Si–O Coordination Comparison')
plt.xlim(2, 8)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"coordination_comparison.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"coordination_comparison.svg"))
plt.close()

# ==========================
# Ring Sizes
# ==========================
plt.figure()
if len(rings_sizes1) > 0:
    plt.bar(rings_sizes1, rings_counts1, alpha=0.5, color='blue', label='Before Amorphous')
if len(rings_sizes2) > 0:
    plt.bar(rings_sizes2, rings_counts2, alpha=0.5, color='red', label='After Amorphous')
plt.xlabel('Ring size')
plt.ylabel('Count')
plt.title('Ring Size Comparison')
plt.xlim(2, 10)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"rings_comparison.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"rings_comparison.svg"))
plt.close()

# ==========================
# Bond Angles
# ==========================
# O–Si–O
plt.figure()
if len(angles_O_Si_O_1) > 0:
    plt.hist(angles_O_Si_O_1, bins=180, alpha=0.5, color='blue', label='Before Amorphous', edgecolor='black')
if len(angles_O_Si_O_2) > 0:
    plt.hist(angles_O_Si_O_2, bins=180, alpha=0.5, color='red', label='After Amorphous', edgecolor='black')
plt.xlabel('Bond angle (degrees)')
plt.ylabel('Frequency')
plt.title('O–Si–O Bond Angle Comparison')
plt.xlim(80, 160)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"angles_comparison_O_Si_O.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"angles_comparison_O_Si_O.svg"))
plt.close()

# Si–O–Si
plt.figure()
if len(angles_Si_O_Si_1) > 0:
    plt.hist(angles_Si_O_Si_1, bins=180, alpha=0.5, color='blue', label='Before Amorphous', edgecolor='black')
if len(angles_Si_O_Si_2) > 0:
    plt.hist(angles_Si_O_Si_2, bins=180, alpha=0.5, color='red', label='After Amorphous', edgecolor='black')
plt.xlabel('Bond angle (degrees)')
plt.ylabel('Frequency')
plt.title('Si–O–Si Bond Angle Comparison')
plt.xlim(90, 180)
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(output_dir,"angles_comparison_Si_O_Si.png"),dpi=600)
plt.savefig(os.path.join(output_dir,"angles_comparison_Si_O_Si.svg"))
plt.close()
print("✅ Analysis complete! High-quality PNG/SVG graphs saved in:", output_dir)